config:
  searcher0:
    proc: 0
    solver: "ransac_solver"
    scenes: ["surface"]
    scene_frame_ids: ["camera/capture0"]
    master_frame_ids: ["camera/master0"]
    solve_frame_id: "camera/capture0"
  searcher1:
    proc: 1
    solver: "zhou_solver"
    scenes: ["surface"]
    scene_frame_ids: ["camera/capture0"]
    master_frame_ids: ["camera/master0"]
  cropper:
    capture_frame_id: "camera"
    source_frame_id: "camera/capture"
    frame_id: "camera/capture0"
    relay: "/rovi/X1"
    ansback: "/rovi/Y1"
  picker:
    multiplex: 1
    solve_frame_id: "camera/capture0"
    reference_frame_id: "solve_check"
    base_frame_id: "base"
  report:
    "altitude": -25
    "width": 1920
    "rows": 4
    recipe: "/dashboard/recipe"
    keys: ["pcount","fitness","rmse","azimuth","rotation","transX","transY","transZ","tcap","tfeat","tmatch"]
    labels: ["点数","一致度","平均誤差","傾き","回転","経由点X","経由点Y","経由点Z","撮影処理時間","特徴処理時間","マッチング処理時間"]
  rsocket:
    base_frame_id: "base"
    source_frame_id: "camera/master0"
    target_frame_id: "camera/capture0/solve0"
    update_frame_id: "tool0_controller"
    check_frame_id: "work_place"
#    post: "rosrun rovi_industrial revolve.py"  #overrides built in post processor

config_tf:
  pallet:
    parent_frame_id: "base"
    transform:
      rotation:
        w: 1.0
        x: 0.0
        y: 0.0
        z: 0.0
      translation:
        x: 0.0
        y: -2000.0
        z: 0.0
  work_place:
    parent_frame_id: "pallet"
  solve_check:
    parent_frame_id: "work_place"
    transform:
      rotation:
        w: 0.0
        x: 0.0
        y: 1.0
        z: 0.0
      translation:
        x: 0.0
        y: 0.0
        z: 500.0
